### ISSUE TITLE
input names different

### ISSUE THREAD

**Issue by mictadlo** [cbcrg/kallisto-nf#2]
Hi,
Should `index` be not called `transcriptome.index` in [line](https://github.com/cbcrg/kallisto-nf/blob/master/kallisto.nf#L97) because in [line](https://github.com/cbcrg/kallisto-nf/blob/master/kallisto.nf#L111) it used as `transcriptome.index` rather than `index`?

Michal

**Comment by evanfloden** [comment]
Yes exactly. Thanks for spotting that and pointing it out 👍
